### ISSUE TITLE
The opening question mark (¿) is wrongly flipped

### ISSUE THREAD

**Issue by fitojb** [marcelommp/Coiny-typeface#6]
Opening question marks are not mirrored versions of _?_ — they are 180 degree-rotated versions of _?_. This means that _¿_ should also hang below the baseline at the same level of lowercase letters with descenders, such as _p_.

![Screenshot from Google Fonts](https://cloud.githubusercontent.com/assets/554953/17049951/e6dc6332-4fb5-11e6-9825-ad2aab259783.png)

**Comment by marcelommp** [comment]
Totally right, thanks.

**Comment by davelab6** [comment]
Tracking the update at https://github.com/google/fonts/issues/334 :)
