### ISSUE TITLE
Vietnamese issue

### ISSUE THREAD

**Issue by crystaltype** [marcelommp/Coiny-typeface#7]
Please see the image
![111](https://cloud.githubusercontent.com/assets/20129845/18838936/664932c4-8433-11e6-9447-86181b115642.png)

**Comment by marcelommp** [comment]
Done plus adjustments in Tamil proportions and others accents.

![captura de tela 2016-10-03 as 19 55 54](https://cloud.githubusercontent.com/assets/12647948/19057053/9100064e-89a3-11e6-9539-76fafa3436e0.png)
